workflows:
  build_webview_app:
    name: Build Webview App
    max_build_duration: 20
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    scripts:
      - echo "Building webview app"
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
